# Generated by Django 2.2 on 2021-03-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20210302_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
    ]
