# Generated by Django 2.2 on 2021-03-06 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20210303_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='サークル画像'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='insta_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='サークル名'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='代表者'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
