# Generated by Django 2.2 on 2021-03-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_auto_20210306_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='slug',
            field=models.SlugField(null=True, verbose_name='スラッグ'),
        ),
    ]
