# Generated by Django 2.2 on 2021-03-06 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0006_auto_20210306_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='circle',
            name='alcohol',
            field=models.IntegerField(choices=[(0, '少なめもしくは無'), (1, 'どちらかといえば少なめ'), (2, '普通'), (3, 'どちらかといえば多め'), (4, '多め')], default=3, verbose_name='飲み会頻度'),
        ),
        migrations.AddField(
            model_name='circle',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='年会費'),
        ),
        migrations.AddField(
            model_name='circle',
            name='gender_rate',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (1, '10%'), (2, '20%'), (3, '30%'), (4, '40%'), (50, '50%'), (6, '60%'), (7, '70%'), (8, '80%'), (9, '90%'), (10, '100%')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='男女比率'),
        ),
        migrations.AddField(
            model_name='circle',
            name='hard',
            field=models.IntegerField(blank=True, choices=[(0, '緩め'), (1, 'どちらかといえば緩め'), (2, '普通'), (3, 'どちらかというとまじめ'), (4, 'まじめ')], default=3, null=True, verbose_name='本気度(厳しさ)'),
        ),
        migrations.AddField(
            model_name='circle',
            name='members_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='人数'),
        ),
    ]
