# Generated by Django 2.2 on 2021-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_auto_20210306_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='practice_date',
            field=models.CharField(default='', max_length=20, verbose_name='活動日'),
        ),
        migrations.AddField(
            model_name='circle',
            name='practice_place',
            field=models.CharField(default='', max_length=20, verbose_name='活動場所'),
        ),
    ]
