# Generated by Django 2.2 on 2021-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0009_auto_20210307_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年会費'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='members_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='人数'),
        ),
    ]
