# Generated by Django 2.2 on 2021-03-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0012_auto_20210316_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='practice_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='活動日'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='practice_place',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='活動場所'),
        ),
    ]
