# Generated by Django 2.2 on 2021-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0013_auto_20210316_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='event',
            field=models.IntegerField(blank=True, choices=[(0, '少なめもしくは無'), (1, 'どちらかといえば少なめ'), (2, '普通'), (3, 'どちらかといえば多め'), (4, '多め')], null=True, verbose_name='イベント頻度'),
        ),
        migrations.AddField(
            model_name='circle',
            name='experienced',
            field=models.IntegerField(blank=True, choices=[(0, '20%以下'), (1, '20% ～ 40%'), (2, '40% ～ 60%'), (3, '60% ～ 80%'), (4, '80%以上')], null=True, verbose_name='テニス経験者率'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='hard',
            field=models.IntegerField(blank=True, choices=[(0, '緩め'), (1, 'どちらかといえば緩め'), (2, '普通'), (3, 'どちらかというとまじめ'), (4, 'まじめ')], default=3, null=True, verbose_name='練習雰囲気'),
        ),
    ]
