# Generated by Django 2.2 on 2021-03-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0014_auto_20210321_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='experienced',
            field=models.IntegerField(blank=True, choices=[(0, '10%以下'), (1, '10% ～ 20%'), (2, '20% ～ 40%'), (3, '40% ～ 60%'), (4, '60%以上')], null=True, verbose_name='テニス経験者率'),
        ),
    ]
